### ISSUE TITLE
Need Datasets and Pre-trained models

### ISSUE THREAD

**Issue by sodhinchu** [albertotestoni/confirm_it#1]
HI,
I am looking for datasets and pre-trained models for my self-learning. Can you please share where can I get that information?
Thank you in advance.

**Comment by albertotestoni** [comment]
Hi,
thank you for your interest in our work! You can find the pre-processed dataset and pre-trained model in this shared directory: https://drive.google.com/drive/folders/1zfkSRuqV_yQHR-1HnSydNub4OOH5wRmN?usp=sharing . 
Please let me know if you need anything else from my side, and feel free to write me an email for any question about this work.

**Comment by sodhinchu** [comment]
Thank you, I am able to download these. I will check and if I need anything further, will email you.
Thank you very much
