### ISSUE TITLE
GuessWhat AI Dataset

### ISSUE THREAD

**Issue by sodhinchu** [albertotestoni/confirm_it#2]
HI,
I have few more queries. Can you please help in understanding them..
1) In the code: model_ensemble_ravi_E_3 is mentioned [config\GamePlay\ensemble], in drive there is a name: model_ensemble_3tasks_mod7_E_28 -> Are these same?

2) There is no guesswhat-lxmert folder in the source code shared - is it shared somewhere on the drive?

3) From where can i get Guesswhat dataset? Also can you please indicate steps for inferencing, training in the README file?

Thank you in advance.

**Comment by albertotestoni** [comment]
Hi,
in short: 1) no, use the one I shared. 2) you should specify the data folder where you put the pre-processed dataset. 3) yes, I'll do it.
I am sorry, the code still needs some cleaning and explanation on how to run the different scripts. The plan was to have the repository fully working by the start of the EMNLP conference (7th November), but I will try to work on it during this week. Please check the repository again in a few days.
Thanks for your understanding.

**Comment by sodhinchu** [comment]
Hi,
Sure thank you for your update. I will check after few days.
Thank you
